src/objects/SunContact__c.object
<CustomObject>
    <description>&quot;Sun Kindergarten&quot; custom contact object</description>
    <fields>
        <fullName>AttendanceGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AttendanceGroup</label>
        <referenceTo>SunGroup__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>AttendanceGroups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SunContact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SunContacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SunGroup__c.object
<CustomObject>
    <description>&quot;Sun Kindergarten&quot; group object</description>
    <fields>
        <fullName>MaxKidsInGroup__c</fullName>
        <defaultValue>15</defaultValue>
        <label>MaxKidsInGroup</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SunGroup</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SunGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SunContactTriggerTestFactory.cls
public with sharing class SunContactTriggerTestFactory {
    public static List<SunContact__c> generateContactsWithGroup(Integer numCases, SunGroup__c newGroup, String recordTypeStr){
        Id recordTypeId = Schema.SObjectType.SunContact__c.getRecordTypeInfosByName().get(recordTypeStr).getRecordTypeId();
        List<SunContact__c> contacts = new List<SunContact__c>();
        for (Integer i=0; i<numCases; i++){
            contacts.add(
                new SunContact__c(
                    Name='Test' + i,
                    RecordTypeId=recordTypeId,
                    AttendanceGroup__c = newGroup.Id
                )
            );
        }
        return contacts;
    }

    public static SunGroup__c generateGroup(String groupName, Integer maxKids){
        SunGroup__c newGroup = new SunGroup__c(
            Name='TestGroup',
            MaxKidsInGroup__c=maxKids
        );
        return newGroup;
    }

    public static void updateGroup(List<SunContact__c> contacts, SunGroup__c newGroup){
        for (SunContact__c c:contacts){
            c.AttendanceGroup__c = newGroup.Id;
        }
    }
}