src/objects/SunContact__c.object
<CustomObject>
    <description>&quot;Sun Kindergarten&quot; custom contact object</description>
    <fields>
        <fullName>AttendanceGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AttendanceGroup</label>
        <referenceTo>SunGroup__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>AttendanceGroups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SunContact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SunContacts</pluralLabel>
    <recordTypes>
        <fullName>Parent</fullName>
        <active>true</active>
        <label>Parent</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SunVisit__c.object
<CustomObject>
    <description>&quot;Sun Kindergarten&quot; visit object</description>
    <fields>
        <fullName>ArrivalTime__c</fullName>
        <defaultValue>TIMENOW()</defaultValue>
        <label>ArrivalTime</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LeavingTime__c</fullName>
        <label>LeavingTime</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Superior__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Superior</label>
        <referenceTo>SunContact__c</referenceTo>
        <relationshipLabel>Visits (as Superior)</relationshipLabel>
        <relationshipName>Superiors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visitor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Visitor</label>
        <referenceTo>SunContact__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>SunVisits</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>SunVisit</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Visit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SunVisits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AttendanceSheetController.cls
/**
 * Created by Ivan.Sokolov on 10.01.2022.
 */

public with sharing class AttendanceSheetController {
    @AuraEnabled(Cacheable=true)
    public static List<SunContact__c> getContactsByGroupId(Id groupId, String dateStr){
        Date dt = Date.valueOf(dateStr);
        return [SELECT Id, Name, (SELECT Id, ArrivalTime__c, LeavingTime__c, Superior__c FROM SunVisits__r WHERE Date__c=:dt) FROM SunContact__c WHERE AttendanceGroup__c=:groupId];
    }

    @AuraEnabled(Cacheable=true)
    public static List<SunContact__c> getParentContacts(){
        Id parentId = Schema.SObjectType.SunContact__c.getRecordTypeInfosByName().get('Parent').getRecordTypeId();
        return [SELECT Id, Name FROM SunContact__c WHERE RecordTypeId=:parentId];
    }

    @AuraEnabled
    public static void addVisit(String visitorId, String visitDate, String arrivalTime, String leavingTime, String superiorId){
        String[] arrivalTimeSplit = arrivalTime.split(':');
        String[] leavingTimeSplit = leavingTime.split(':');
        insert new SunVisit__c(
                Visitor__c=Id.valueOf(visitorId),
                Date__c=Date.valueOf(visitDate),
                ArrivalTime__c=Time.newInstance(
                        Integer.valueOf(arrivalTimeSplit[0]),
                        Integer.valueOf(arrivalTimeSplit[1]),
                        0,
                        0
                ),
                LeavingTime__c=Time.newInstance(
                        Integer.valueOf(leavingTimeSplit[0]),
                        Integer.valueOf(leavingTimeSplit[1]),
                        0,
                        0
                ),
                Superior__c=Id.valueOf(superiorId)
        );
    }
}